### ISSUE TITLE
jquery PRIMO plugin

### ISSUE THREAD

**Issue by danizen** [mehmetc/jQuery.PRIMO#11]
Is this compatible with the new PRIMO UI?   It is not automatically loaded, but should be loadable with the provided JavaScript from the PRIMO hosted copy.   Has this been tested?

Thanks,

Dan Davis

**Comment by mehmetc** [comment]
The new UI has a completely different architecture and for now I do not see a need to port this. I'm going to start my first new UI project in a week. So, my opinion might be completely different in a month or two ...

The library does not get loaded automatically because a lot of people don't customize PRIMO.
If you have trouble loading the JS library we can setup a 5-10 min call and I can get you started. 

Mehmet
