### ISSUE TITLE
add search tab to the model?

### ISSUE THREAD

**Issue by andymackinnon** [mehmetc/jQuery.PRIMO#9]
hi mehmet,

a while back you helped suggest a way of implementing a jquery-based prompt to users to login to see extended results etc.  that's working well in our dev environment but our local user group have requested that it only display when particular search tabs are active.  i've looked at the documentation and model and it seems that the currently active search tab isn't included in the jquery model - would it be possible to add this, possibly as an attribute of the view (e.g. jQuery.PRIMO.session.view.tab.code) ?

thanks very much for considering,

andy

**Comment by mehmetc** [comment]
Hi Andy,

You can get the tab from jQuery.PRIMO.query.tab but you are right that the object didn't initialize correctly on the home screen. I've corrected this. I'm afraid that this will not be in the August release but you can use it by overwriting the installed version if you have access to the server or link directly to the library on github instead of the local version.

<script type='text/javascript' src='https://cdn.rawgit.com/mehmetc/jQuery.PRIMO/master/dist/jQuery.PRIMO.min.js'></script>

Hope this is what you are looking for.

Mehmet
